" Use no compatible mode
set nocompatible

" Filetype off is required by vundle
filetype off

" Load vundles from plugin file
if filereadable(expand("~/.vim/vundles.vim"))
	" Set the runtime path to include Vundle and initialize
	set rtp+=~/.vim/bundle/Vundle.vim
	call vundle#begin()

	" Load plugins
	source ~/.vim/vundles.vim

	" Load local bundles
	if filereadable(expand("~/.vim/vundles.local"))
		source ~/.vim/vundles.local
	endif

	" All of your Plugins must be added before the following line
	call vundle#end()
elseif filereadable("/etc/vim/vundles.vim")
	" Set the runtime path to include Vundle and initialize
	set rtp+=/etc/vim/bundle/Vundle.vim
	call vundle#begin("/etc/vim/bundle/")

	" Load plugins
	source /etc/vim/vundles.vim

	" All of your Plugins must be added before the following line
	call vundle#end()
endif

" add .vim folder to runtime (for neovim)
set rtp+=~/.vim
" use indentation plugin
filetype plugin indent on

" use 256 colors in vim
set t_Co=256
" use dark background in vim
set background=dark

" Set theme for vim
colorscheme base16-oceanicnext

" use powerline font in airline
let g:airline_powerline_fonts=1
" use base16 theme for airline
let g:airline_theme="base16"
" set default indentation to two spaces
set shiftwidth=2
" show the width of TAB as two spaces
set tabstop=2

" Use the OS clipboard by default (on versions compiled with `+clipboard`)
set clipboard=unnamed
" Enhance command-line completion
set wildmenu
" Allow backspace in insert mode
set backspace=indent,eol,start
" Optimize for fast terminal connections
set ttyfast
" Add the g flag to search/replace by default
set gdefault
" Use UTF-8 without BOM
set encoding=utf-8 nobomb
" Change mapleader
let mapleader=","
" Don’t add empty newlines at the end of files
set binary
set noeol

" Centralize backups, swapfiles and undo history
if filereadable("~/.vim/backups")
	set backupdir=~/.vim/backups
endif

if filereadable("~/.vim/swaps")
	set directory=~/.vim/swaps
endif

if exists("&undodir")
	set undodir=~/.vim/undo
endif

" Don’t create backups when editing files in certain directories
set backupskip=/tmp/*,/private/tmp/*

" Respect modeline in files
set modeline
set modelines=4
" Enable per-directory .vimrc files and disable unsafe commands in them
set exrc
set secure
" Enable line numbers
set number
" Enable syntax highlighting
syntax on
" Highlight searches
set hlsearch
" Ignore case of searches
set ignorecase
" Highlight dynamically as pattern is typed
set incsearch
" Always show status line
set laststatus=2
" Enable mouse in all modes
set mouse=a
" Disable error bells
set noerrorbells
" Don’t reset cursor to start of line when moving around.
set nostartofline
" Show the cursor position
set ruler
" Don’t show the intro message when starting Vim
set shortmess=atI
" Show the current mode
set showmode
" Show the filename in the window titlebar
set title
" Show the (partial) command as it’s being typed
set showcmd
" Start scrolling three lines before the horizontal window border
set scrolloff=3

" Keybinding
nnoremap <Leader>f :NERDTreeToggle<Enter>

" Local config
if filereadable($HOME . "/.vimrc.local")
    source ~/.vimrc.local
endif
